spring:
        application:
                name: be_camphub
        
        datasource:
                url: jdbc:postgresql://localhost:5432/camphub
                username: postgres
                password: 3008
                driver-class-name: org.postgresql.Driver
        jpa:
                hibernate:
                        ddl-auto: update
                show-sql: true
server:
        port: 8081

cloudinary:
        cloudName: "daxuovzwp"
        apiKey: "961126652335228"
        secretKey: "W5hSkCyKOPHKaPnyhBcMODhKjm8"
        secure: true